### ISSUE TITLE
Invite Rebecca Welkens

### ISSUE THREAD

**Issue by beringel** [Forgeries-and-Networks/.github#9]
Dear @dvasques83 , 

granted that this is planned, would you please invite Rebecca Welkens to this project? From what I can see you are an administrator of this project and have the rights to so. 

Also -- and I am going to create a new issue for this for all other team members regarding the issues of work package 1 as well -- could you please treat this issue/task as an test object and use statuses, priorities etc. to 

a) familiarize yourself with the functions and 
b) to let me know/see if this is working.

Thanks so much!
Lara

**Comment by dvasques83** [comment]
This is great, @beringel, thanks a lot!

I have invited Rebecca so will close the issue. The student assistants will just work with the transcriptions and they already have access to that GitHub repository, so don't need to invite them to this one. 
Thanks again!
